apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: cluster-2
spec:
  id: a-team-cluster-2
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: medium
    minNodeCount: 3
    namespaces:
      - dev
      - production
      - crossplane-system
    apps:
      externalSecrets:
        enabled: true
        store: true
        secrets:
          - fromSecret: dynatrace-tokens
            toSecret: a-team-cluster-2
            toNamespace: dynatrace
          - fromSecret: dynatrace-tokens
            toSecret: dynatrace-tokens-2
            toNamespace: dynatrace
      traefik:
        enabled: true
      dynatrace:
        enabled: true
        apiUrl: https://ypd98635.sprint.dynatracelabs.com/api
    creds:
      name: aws-creds
      namespace: crossplane-system
      keys:
        - creds
        - accessKeyID
        - secretAccessKey
