apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: crossplane-observability-demo
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/k8s-app-enabled: "true"
spec:
  apiUrl: https://ypd98635.sprint.dynatracelabs.com/api
  oneAgent:
    cloudNativeFullStack:
      image: ""
  activeGate:
    capabilities:
      - kubernetes-monitoring
      - routing
      - metrics-ingest
      - dynatrace-api
    image: ""
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi
